apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minotaur-sapient

resources:
  - ../../base
  - envs


patches:
  - path: ./patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: minotaur-sapient
  - path: ./patches/service-patch.yaml
    target:
      kind: Service
      name: minotaur-sapient
  - path: ./patches/namespace-patch.yaml
    target:
      kind: Namespace
      name: minotaur-sapient

images:
  - name: devavaxiaregistry.azurecr.io/minotaur-sapient
    newTag: 75b1e0a37508709dbcc44ec0788a4bfeafe1351e