apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minotaur-sapient

resources:
  - ../../base
  - envs

helmCharts:
- name: mysql
  version: 8.0.0  # Specify the chart version explicitly
  repo: https://charts.bitnami.com/bitnami  # Add repo if chart is remote
  releaseName: mysql
  namespace: minotaur-sapient
  valuesInline:
    auth:
      database: test
      password: Avaxia_root@pswd
      username: mysql
    primary:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi

helmGlobals:
  chartHome: charts  # Only needed for local charts

patches:
  - path: ./patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: minotaur-sapient
  - path: ./patches/service-patch.yaml
    target:
      kind: Service
      name: minotaur-sapient
  - path: ./patches/namespace-patch.yaml
    target:
      kind: Namespace
      name: minotaur-sapient

images:
  - name: devavaxiaregistry.azurecr.io/minotaur-sapient
    newTag: 75b1e0a37508709dbcc44ec0788a4bfeafe1351e