apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minotaur-sapient
resources:
  - ../../base
  - envs

helmCharts:
- includeCRDs: true
  name: mysql
  namespace: minautor-sapient
  releaseName: mysql
  valuesInline:
    auth:
      database: test
      enableMysqlUser: true
      password: Avaxia_root@pswd
      mysqlPassword: Avaxia_root@pswd
      username: mysql
    primary:
      initdb:
        scriptsConfigMap: minautor-init-scripts
      persistence:
        enabled: true
        existingClaim: ""
        size: 10Gi
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
            
helmGlobals:
  chartHome: charts



patches:
  - path: ./patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: minotaur-sapient
      version: v1
  - path: ./patches/service-patch.yaml
    target:
      kind: Service
      name: minotaur-sapient
      version: v1
  - path: ./patches/namespace-patch.yaml
    target:
      kind: Namespace
      name: minotaur-sapient
      version: v1 
images:
  - name: devavaxiaregistry.azurecr.io/minotaur-sapient
    newTag: 75b1e0a37508709dbcc44ec0788a4bfeafe1351e
