apiVersion: v1
kind: ConfigMap
metadata:
  name: minotaur-init-scripts
  namespace: minotaur-sapient
data:
  create-databases.sql: |

    CREATE DATABASE IF NOT EXISTS `db_config` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    CREATE USER IF NOT EXISTS 'dispatcher_db'@'%' IDENTIFIED BY 'disp_schedule_01';
    GRANT ALL PRIVILEGES ON db_config.* TO 'dispatcher_db'@'%';
    FLUSH PRIVILEGES;

    CREATE DATABASE IF NOT EXISTS `notification` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    CREATE USER IF NOT EXISTS 'u_notification'@'%' IDENTIFIED BY 'notification';
    GRANT ALL PRIVILEGES ON notification.* TO 'u_notification'@'%';
    FLUSH PRIVILEGES;   

    CREATE DATABASE IF NOT EXISTS `minotaur_reports_rbac` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    CREATE USER IF NOT EXISTS 'u_rbac'@'%' IDENTIFIED BY 'rbac';
    GRANT ALL PRIVILEGES ON minotaur_reports_rbac.* TO 'u_rbac'@'%';
    GRANT SUPER ON *.* TO 'u_rbac'@'%';
    FLUSH PRIVILEGES;
    
    CREATE DATABASE IF NOT EXISTS `minotaur_reports_core` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    CREATE USER IF NOT EXISTS 'u_mca'@'%' IDENTIFIED BY 'Q8i1*f&e&NGSqiW0';
    GRANT ALL PRIVILEGES ON minotaur_reports_core.* TO 'u_mca'@'%';
    FLUSH PRIVILEGES;