apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minotaur-config
resources:
  - ../../base
  - envs


patches:
  - path: ./patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: minotaur-config
      version: v1
  - path: ./patches/service-patch.yaml
    target:
      kind: Service
      name: minotaur-config
      version: v1
  - path: ./patches/namespace-patch.yaml
    target:
      kind: Namespace
      name: minotaur-config
      version: v1

images:
  - name: devavaxiaregistry.azurecr.io/minotaur-config
    newTag: 75b1e0a37508709dbcc44ec0788a4bfeafe1351e
