
- op: replace
  path: /spec/template/spec/containers/0/image
  value: devavaxiaregistry.azurecr.io/minotaur-extractor

- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name:  env-configs
    - secretRef:
        name: extractor-secrets

- op: add 
  path: /spec/revisionHistoryLimit
  value: 2  

- op: replace
  path: /metadata/name
  value: minotaur-extractor
- op: replace
  path: /metadata/labels/app
  value: minotaur-extractor
- op: replace
  path: /spec/replicas
  value: 1
- op: replace
  path: /spec/selector/matchLabels/app
  value: minotaur-extractor
- op: replace
  path: /spec/template/metadata/labels/app
  value: minotaur-extractor
- op: replace
  path: /spec/template/spec/containers/0/name
  value: minotaur-extractor
- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: 5000
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always
