apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-minotaur-dispatcher
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec: 
  destination:
    namespace: minotaur-dispatcher
    server: {{ .Values.spec.destination.server }}
  project: minotaur
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: minautor/microservices/dispatcher/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true