apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-minotaur-sapient
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minotaur-sapient
    server: {{ .Values.spec.destination.server }}
  project: minotaur
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: minotaur/microservices/sapient/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      enableHelm: true  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true