apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
- envs:
  - config.env 
  name: env-configs
  namespace: minotaur-teamsbot

secretGenerator:
  - name: teamsbot-secrets
    envs:
      - secrets.env
    namespace: minotaur-teamsbot


generatorOptions:
  disableNameSuffixHash: true
