apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
- envs:
  - config.env 
  name: env-configs
  namespace: minotaur-sapient

secretGenerator:
  - name: sapient-secrets
    envs:
      - secrets.env
    namespace: minotaur-sapient


generatorOptions:
  disableNameSuffixHash: true
