apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minotaur-frontend
resources:
  - ../../base
  - envs


patches:
  - path: ./patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: minotaur-frontend
      version: v1
  - path: ./patches/service-patch.yaml
    target:
      kind: Service
      name: minotaur-frontend
      version: v1
  - path: ./patches/namespace-patch.yaml
    target:
      kind: Namespace
      name: minotaur-frontend
      version: v1 
  - path: ./patches/ingress-patch.yaml
    target:
      kind: Ingress
      name: minotaur-frontend
images:
  - name: devavaxiaregistry.azurecr.io/minotaur-frontend
    newTag: 75b1e0a37508709dbcc44ec0788a4bfeafe1351e
