apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - service.yaml
    - deployment.yaml
    - namespace.yaml
    - mysql-cm.yaml


generatorOptions:
 disableNameSuffixHash: true

